### PR TITLE
Add support for Xcode 7.3

### PR DESCRIPTION
**Pull request by k06a**

### CODE REVIEW

**Comment by k06a** [comment]
@designatednerd please review this tiny PR :)

**Comment by vokal-isaac** [comment]
LGTM

**Comment by designatednerd** [comment]
@k06a ya beat me to the punch! LGTM 2! @brockboland @chillpop when you have a moment

**Comment by brockboland** [comment]
:clap:

**Comment by k06a** [comment]
Thanks!

**Comment by podkovyrin** [comment]
```shell
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`
```

**Pull request merged**
