### PR TITLE
Add Xcode 6.2 UUID

### PR DESCRIPTION
**Pull request by designatednerd**

### CODE REVIEW

**Comment by designatednerd** [comment]
Welp, I figured out why this wasn't working with Xcode 6.2. @vokal/ios-developers "code review" in the morning?

**Comment by vokal-isaac** [comment]
Is there a 6.3 UUID that can be added now, or does that have to wait for a final release?

**Comment by designatednerd** [comment]
Has to wait for final release, the beta UUIDs and finals are usually different.

**Comment by vokal-isaac** [comment]
In that case,
goats-1024_181263k

**Pull request merged**
